language: python

os:
    - linux

python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7

matrix:
  include:
    - env: TOXENV=lint,security,setuppy,manifest

env:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
    - pip install tox

script: tox
